// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BookInfo(arg1, arg2) {
  return window['go']['main']['App']['BookInfo'](arg1, arg2);
}

export function DefaultSettings() {
  return window['go']['main']['App']['DefaultSettings']();
}

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Library() {
  return window['go']['main']['App']['Library']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function QimaoAdaptBooks(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['QimaoAdaptBooks'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function QimaoAdaptConfig() {
  return window['go']['main']['App']['QimaoAdaptConfig']();
}

export function QimaoRankBooks(arg1, arg2) {
  return window['go']['main']['App']['QimaoRankBooks'](arg1, arg2);
}

export function RankingBooks(arg1) {
  return window['go']['main']['App']['RankingBooks'](arg1);
}

export function RankingCategories() {
  return window['go']['main']['App']['RankingCategories']();
}

export function RemoveLibraryItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveLibraryItem'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function SetShortdramaIgnored(arg1) {
  return window['go']['main']['App']['SetShortdramaIgnored'](arg1);
}

export function ShortdramaSearch(arg1) {
  return window['go']['main']['App']['ShortdramaSearch'](arg1);
}
