// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {qimao} from '../models';

export function BookInfo(arg1:string,arg2:string):Promise<main.BookInfo>;

export function DefaultSettings():Promise<main.Settings>;

export function Download(arg1:string,arg2:string):Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function Library():Promise<Array<main.LibraryItem>>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function QimaoAdaptBooks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<main.AdaptPageResult>;

export function QimaoAdaptConfig():Promise<Array<qimao.AdaptFilterGroup>>;

export function QimaoRankBooks(arg1:string,arg2:string):Promise<Array<main.RankedBook>>;

export function RankingBooks(arg1:string):Promise<Array<main.RankedBook>>;

export function RankingCategories():Promise<Array<main.RankCategory>>;

export function RemoveLibraryItem(arg1:string,arg2:boolean):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<main.SearchItem>>;

export function SetSettings(arg1:main.Settings):Promise<void>;

export function SetShortdramaIgnored(arg1:boolean):Promise<void>;

export function ShortdramaSearch(arg1:string):Promise<Array<main.ShortdramaIP>>;
